# Generated by Django 5.0.1 on 2024-09-15 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpecialistTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of object create",
                        verbose_name="Create time",
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of object update",
                        verbose_name="Update time",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Specialist type name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Specialist type",
                "verbose_name_plural": "Specialist types",
                "db_table": "specialist_types",
                "db_table_comment": "Table include data of all specialist types",
                "ordering": ("update", "name"),
                "get_latest_by": "update",
            },
        ),
        migrations.CreateModel(
            name="WorkingDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of object create",
                        verbose_name="Create time",
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of object update",
                        verbose_name="Update time",
                    ),
                ),
                ("order", models.SmallIntegerField(verbose_name="Working days order")),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Working day name"),
                ),
                (
                    "shortened_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Shortened name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Working day",
                "verbose_name_plural": "Working days",
                "db_table": "working_days",
                "db_table_comment": "Table include data of working days",
                "ordering": ("order",),
                "get_latest_by": "order",
            },
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of object create",
                        verbose_name="Create time",
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of object update",
                        verbose_name="Update time",
                    ),
                ),
                ("fio", models.CharField(max_length=255)),
                (
                    "specialist_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.specialisttypes",
                        verbose_name="Specialist type",
                    ),
                ),
                (
                    "working_days",
                    models.ManyToManyField(
                        blank=True,
                        to="employees.workingdays",
                        verbose_name="Working days",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employees",
                "db_table_comment": "Table include data of all employees",
                "ordering": ("update", "fio"),
                "get_latest_by": "update",
            },
        ),
    ]
