# Generated by Django 5.0.1 on 2024-09-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialisttypes",
            name="description",
            field=models.TextField(
                default="", verbose_name="Specialist type description"
            ),
        ),
    ]
