# Generated by Django 5.0.1 on 2024-09-09 22:26

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of object create",
                        verbose_name="Create time",
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of object update",
                        verbose_name="Update time",
                    ),
                ),
                (
                    "fio",
                    models.CharField(max_length=500, verbose_name="Full name visitor"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(blank=True, max_length=254, verbose_name="Mail"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Address"
                    ),
                ),
                (
                    "is_child",
                    models.BooleanField(default=False, verbose_name="Is children?"),
                ),
                (
                    "children",
                    models.ManyToManyField(
                        blank=True, to="visitors.visitor", verbose_name="Children"
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitor",
                "verbose_name_plural": "Visitors",
                "db_table": "visitors",
                "db_table_comment": "Table include data of all visitors",
                "ordering": ("update", "fio"),
                "get_latest_by": "update",
            },
        ),
    ]
