# Generated by Django 5.0.1 on 2024-09-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("visitors.visitor",),
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("visitors.visitor",),
        ),
        migrations.AddField(
            model_name="visitor",
            name="reason_for_request",
            field=models.TextField(
                blank=True, default="", verbose_name="Reason for request"
            ),
        ),
    ]
