# Generated by Django 5.0.1 on 2024-09-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                related_name="child",
                to="visitors.visitor",
                verbose_name="Children",
            ),
        ),
    ]
