# Generated by Django 5.0.1 on 2024-09-16 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        ("visitors", "0002_alter_visitor_children"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of object create",
                        verbose_name="Create time",
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of object update",
                        verbose_name="Update time",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Session name")),
                ("description", models.TextField(verbose_name="Session description")),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Visit session",
                "verbose_name_plural": "Visits sessions",
                "db_table": "visit_sessions",
                "db_table_comment": "Table include data of all visits session",
                "ordering": ("create",),
                "get_latest_by": "create",
            },
        ),
        migrations.CreateModel(
            name="TypeVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of object create",
                        verbose_name="Create time",
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of object update",
                        verbose_name="Update time",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Type name")),
                ("description", models.TextField(verbose_name="Description")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Type visit",
                "verbose_name_plural": "Visits types",
                "db_table": "type_visit",
                "db_table_comment": "Table include data of all type of visits",
                "ordering": ("create",),
                "get_latest_by": "create",
            },
        ),
        migrations.CreateModel(
            name="Visits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of object create",
                        verbose_name="Create time",
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of object update",
                        verbose_name="Update time",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="DateTime of visit")),
                (
                    "accountable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.employees",
                        verbose_name="Accountable",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="visitors.child",
                        verbose_name="Child",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visit",
                "verbose_name_plural": "Visits",
                "db_table": "visits",
                "db_table_comment": "Table include data of all visits",
                "ordering": ("datetime",),
                "get_latest_by": "datetime",
            },
        ),
    ]
