# Generated by Django 5.0.1 on 2024-09-16 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visits",
            options={
                "get_latest_by": "update",
                "ordering": ("update",),
                "verbose_name": "Visit",
                "verbose_name_plural": "Visits",
            },
        ),
        migrations.RemoveField(
            model_name="visits",
            name="datetime",
        ),
        migrations.CreateModel(
            name="TimeVisits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of object create",
                        verbose_name="Create time",
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of object update",
                        verbose_name="Update time",
                    ),
                ),
                ("time", models.TimeField(verbose_name="Time of visit")),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.workingdays",
                        verbose_name="Date of visit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="visits",
            name="time_visit",
            field=models.ManyToManyField(
                to="visits.timevisits", verbose_name="Visits time"
            ),
        ),
    ]
