# Generated by Django 5.0.1 on 2024-09-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0002_alter_visits_options_remove_visits_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visits",
            name="time_visit",
        ),
        migrations.AddField(
            model_name="timevisits",
            name="time_visit",
            field=models.ManyToManyField(
                to="visits.visits", verbose_name="Visits time"
            ),
        ),
    ]
