# Generated by Django 5.0.1 on 2024-09-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0003_remove_visits_time_visit_timevisits_time_visit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timevisits",
            name="time_visit",
        ),
        migrations.AddField(
            model_name="visits",
            name="time_visit",
            field=models.ManyToManyField(
                to="visits.timevisits", verbose_name="Visits time"
            ),
        ),
    ]
