# Generated by Django 5.0.1 on 2024-09-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0004_remove_timevisits_time_visit_visits_time_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="visits",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="visits.session",
                verbose_name="Session",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visits",
            name="type_visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="visits.typevisit",
                verbose_name="Visit type",
            ),
            preserve_default=False,
        ),
    ]
